//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Einschreibung
    {
        public int EinschreibungID { get; set; }
        public Nullable<decimal> Noten { get; set; }
        public int KursID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        public virtual Student Student { get; set; }
    }
}
