//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxor.Models
{
    using System;
    
    public enum KursEbene : byte
    {
        Anfänger = 1,
        Mittlere = 2,
        Fortgeschritten = 3
    }
}
