//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luxor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurs()
        {
            this.Einschreibungs = new HashSet<Einschreibung>();
        }
    
        public int KursID { get; set; }
        public string Titel { get; set; }
        public Nullable<int> Kredite { get; set; }
        public string KursBeschreibung { get; set; }
        public Nullable<int> Preis { get; set; }
        public Nullable<KursEbene> Ebene { get; set; }
        public Nullable<bool> IstKursAktiv { get; set; }
        public Nullable<int> Level2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Einschreibung> Einschreibungs { get; set; }
        public virtual CourseLevel CourseLevel { get; set; }
    }
}
